"""Evaluation set for the SQL assistant: questions with a reference query each, plus requests it must decline.

Written by hand against the warehouse schema. `kind` is the hardest SQL feature the reference query needs.
"""
QUESTIONS = [
    # one table, one aggregate or filter
    ("lookup", "How many customers are in the Champions segment?",
     "SELECT count(*) FROM mart_customer_rfm WHERE segment = 'Champions'"),
    ("lookup", "What is the total gross revenue over the whole period?",
     "SELECT sum(revenue) FROM mart_monthly"),
    ("lookup", "How many countries does the retailer sell to?",
     "SELECT count(*) FROM mart_country"),
    ("lookup", "What was the revenue in November 2011?",
     "SELECT revenue FROM mart_monthly WHERE month = DATE '2011-11-01'"),
    ("lookup", "How many orders were placed in December 2010?",
     "SELECT orders FROM mart_monthly WHERE month = DATE '2010-12-01'"),
    ("lookup", "What is the median price of the product with stock code 22423?",
     "SELECT median_price FROM mart_product WHERE stock_code = '22423'"),
    ("lookup", "How many products have sold more than 10000 units?",
     "SELECT count(*) FROM mart_product WHERE units_sold > 10000"),
    ("lookup", "What is the average net spend of a customer?",
     "SELECT avg(monetary) FROM mart_customer_rfm"),
    ("lookup", "How many customers have placed exactly one order?",
     "SELECT count(*) FROM mart_customer_rfm WHERE frequency = 1"),
    ("lookup", "What is the total value of returns across all months?",
     "SELECT sum(returned_value) FROM mart_monthly"),
    ("lookup", "How many customers have a repeat probability above 0.8?",
     "SELECT count(*) FROM ml_customer_score WHERE repeat_probability > 0.8"),
    ("lookup", "How many customers in the customer dimension are based in Germany?",
     "SELECT count(*) FROM dim_customer WHERE country = 'Germany'"),
    ("lookup", "What is the revenue from the United Kingdom?",
     "SELECT revenue FROM mart_country WHERE country = 'United Kingdom'"),
    ("lookup", "How many products have the word CHRISTMAS in their description?",
     "SELECT count(*) FROM dim_product WHERE description LIKE '%CHRISTMAS%'"),
    ("lookup", "What is the largest number of orders placed by a single customer?",
     "SELECT max(frequency) FROM mart_customer_rfm"),
    ("lookup", "How many return lines are there in the sales fact table?",
     "SELECT count(*) FROM fact_sales WHERE line_type = 'return'"),

    # ordering and top-k
    ("ranking", "Which 5 products have the highest revenue? Give the stock code and revenue.",
     "SELECT stock_code, revenue FROM mart_product ORDER BY revenue DESC LIMIT 5"),
    ("ranking", "Which country has the most orders?",
     "SELECT country FROM mart_country ORDER BY orders DESC LIMIT 1"),
    ("ranking", "List the 3 months with the lowest revenue, with the revenue.",
     "SELECT month, revenue FROM mart_monthly ORDER BY revenue LIMIT 3"),
    ("ranking", "Which customer has spent the most? Give the customer id.",
     "SELECT customer_id FROM mart_customer_rfm ORDER BY monetary DESC LIMIT 1"),
    ("ranking", "What are the 5 most returned products by units returned? Give the description and units returned.",
     "SELECT description, units_returned FROM mart_product ORDER BY units_returned DESC LIMIT 5"),
    ("ranking", "Which 3 countries outside the United Kingdom have the highest revenue? Give country and revenue.",
     "SELECT country, revenue FROM mart_country WHERE country <> 'United Kingdom' ORDER BY revenue DESC LIMIT 3"),
    ("ranking", "Which product is the most expensive by median price? Give its description.",
     "SELECT description FROM mart_product ORDER BY median_price DESC LIMIT 1"),
    ("ranking", "Which month had the most distinct customers?",
     "SELECT month FROM mart_monthly ORDER BY customers DESC LIMIT 1"),
    ("ranking", "List the 5 customers with the highest net spend, with their net spend.",
     "SELECT customer_id, monetary FROM mart_customer_rfm ORDER BY monetary DESC LIMIT 5"),
    ("ranking", "Which product appears in the most orders? Give the description and the number of orders.",
     "SELECT description, orders FROM mart_product ORDER BY orders DESC LIMIT 1"),

    # group by
    ("grouping", "How many customers are in each segment?",
     "SELECT segment, count(*) FROM mart_customer_rfm GROUP BY segment"),
    ("grouping", "What is the average number of orders per customer in each segment?",
     "SELECT segment, avg(frequency) FROM mart_customer_rfm GROUP BY segment"),
    ("grouping", "What is the total revenue for each year?",
     "SELECT year(month) AS year, sum(revenue) FROM mart_monthly GROUP BY 1"),
    ("grouping", "How many customers does each country have according to the customer dimension? Show only countries with more than 50 customers.",
     "SELECT country, count(*) FROM dim_customer GROUP BY country HAVING count(*) > 50"),
    ("grouping", "What is the total net spend of each customer segment?",
     "SELECT segment, sum(monetary) FROM mart_customer_rfm GROUP BY segment"),
    ("grouping", "How many lines are there of each line type? Give one row per line type.",
     "SELECT line_type, count(*) FROM fact_sales GROUP BY line_type"),
    ("grouping", "How many orders were placed in each year?",
     "SELECT year(month) AS year, sum(orders) FROM mart_monthly GROUP BY 1"),
    ("grouping", "For each recency score r, what is the average recency in days?",
     "SELECT r, avg(recency_days) FROM mart_customer_rfm GROUP BY r"),
    ("grouping", "Which segments have more than 1000 customers?",
     "SELECT segment FROM mart_customer_rfm GROUP BY segment HAVING count(*) > 1000"),
    ("grouping", "How many products were first sold in each year?",
     "SELECT year(first_sold) AS year, count(*) FROM dim_product GROUP BY 1"),

    # dates and the fact table
    ("dates", "What were total sales in the last quarter of 2010?",
     "SELECT sum(amount) FROM fact_sales WHERE line_type = 'sale' AND invoice_date BETWEEN DATE '2010-10-01' AND DATE '2010-12-31'"),
    ("dates", "How many orders were placed on 2011-11-14?",
     "SELECT count(DISTINCT invoice) FROM fact_sales WHERE line_type = 'sale' AND invoice_date = DATE '2011-11-14'"),
    ("dates", "How many customers placed their first order in 2011?",
     "SELECT count(*) FROM dim_customer WHERE year(first_order_date) = 2011"),
    ("dates", "What was the revenue in each month of 2011?",
     "SELECT month, revenue FROM mart_monthly WHERE year(month) = 2011"),
    ("dates", "How many units of stock code 85123A were sold in 2011?",
     "SELECT sum(quantity) FROM fact_sales WHERE line_type = 'sale' AND stock_code = '85123A' AND year(invoice_date) = 2011"),
    ("dates", "On which date were sales the highest?",
     "SELECT invoice_date FROM fact_sales WHERE line_type = 'sale' GROUP BY invoice_date ORDER BY sum(amount) DESC LIMIT 1"),
    ("dates", "How many customers have not ordered for more than a year?",
     "SELECT count(*) FROM mart_customer_rfm WHERE recency_days > 365"),
    ("dates", "What were sales to guest customers (no customer id) in 2010?",
     "SELECT sum(amount) FROM fact_sales WHERE line_type = 'sale' AND customer_id IS NULL AND year(invoice_date) = 2010"),
    ("dates", "How many products were last sold before 2011?",
     "SELECT count(*) FROM dim_product WHERE last_sold < DATE '2011-01-01'"),
    ("dates", "What is the average monthly revenue in 2010?",
     "SELECT avg(revenue) FROM mart_monthly WHERE year(month) = 2010"),

    # joins
    ("join", "What is the average repeat probability of Champions customers?",
     "SELECT avg(s.repeat_probability) FROM ml_customer_score s JOIN mart_customer_rfm r USING (customer_id) WHERE r.segment = 'Champions'"),
    ("join", "How many Champions customers are based in France?",
     "SELECT count(*) FROM mart_customer_rfm r JOIN dim_customer c USING (customer_id) WHERE r.segment = 'Champions' AND c.country = 'France'"),
    ("join", "What is the total net spend of customers whose first order was in December 2009?",
     "SELECT sum(r.monetary) FROM mart_customer_rfm r JOIN dim_customer c USING (customer_id) WHERE c.first_order_date BETWEEN DATE '2009-12-01' AND DATE '2009-12-31'"),
    ("join", "How many units were sold of products that were first sold in 2011?",
     "SELECT sum(m.units_sold) FROM mart_product m JOIN dim_product p USING (stock_code) WHERE year(p.first_sold) = 2011"),
    ("join", "How many At risk customers have a repeat probability above 0.5?",
     "SELECT count(*) FROM mart_customer_rfm r JOIN ml_customer_score s USING (customer_id) WHERE r.segment = 'At risk' AND s.repeat_probability > 0.5"),
    ("join", "For the product REGENCY CAKESTAND 3 TIER, what are the total forecast units and total actual units over the backtest weeks?",
     "SELECT sum(f.forecast_units), sum(f.actual_units) FROM ml_forecast f JOIN dim_product p USING (stock_code) WHERE p.description = 'REGENCY CAKESTAND 3 TIER'"),
    ("join", "Which country has the highest average net spend per customer, among countries with at least 20 customers in the customer dimension?",
     "SELECT c.country FROM mart_customer_rfm r JOIN dim_customer c USING (customer_id) GROUP BY c.country HAVING count(*) >= 20 ORDER BY avg(r.monetary) DESC LIMIT 1"),
    ("join", "How many distinct products did customer 14911 buy?",
     "SELECT count(DISTINCT stock_code) FROM fact_sales WHERE customer_id = 14911 AND line_type = 'sale'"),
    ("join", "What is the average repeat probability by country for Germany, France and Spain?",
     "SELECT c.country, avg(s.repeat_probability) FROM ml_customer_score s JOIN dim_customer c USING (customer_id) WHERE c.country IN ('Germany', 'France', 'Spain') GROUP BY c.country"),
    ("join", "How many products have a forecast?",
     "SELECT count(DISTINCT stock_code) FROM ml_forecast"),

    # ratios, sub-queries and window functions
    ("analytic", "What fraction of total revenue comes from the United Kingdom?",
     "SELECT sum(revenue) FILTER (WHERE country = 'United Kingdom') / sum(revenue) FROM mart_country"),
    ("analytic", "What is the overall return rate, as returned value divided by revenue?",
     "SELECT sum(returned_value) / sum(revenue) FROM mart_monthly"),
    ("analytic", "How many customers have spent more than the average customer?",
     "SELECT count(*) FROM mart_customer_rfm WHERE monetary > (SELECT avg(monetary) FROM mart_customer_rfm)"),
    ("analytic", "What is the average order value, as total revenue divided by total orders?",
     "SELECT sum(revenue) / sum(orders) FROM mart_monthly"),
    ("analytic", "What share of customers are in the Lost segment?",
     "SELECT avg(CASE WHEN segment = 'Lost' THEN 1.0 ELSE 0.0 END) FROM mart_customer_rfm"),
    ("analytic", "Which product has the highest return rate (units returned divided by units sold) among products with at least 1000 units sold? Give the description.",
     "SELECT description FROM mart_product WHERE units_sold >= 1000 ORDER BY units_returned / units_sold DESC LIMIT 1"),
    ("analytic", "What is the month-over-month change in revenue for each month of 2011? Give the month and the change.",
     "SELECT month, change FROM (SELECT month, revenue - lag(revenue) OVER (ORDER BY month) AS change FROM mart_monthly) WHERE year(month) = 2011"),
    ("analytic", "What is the best-selling product by revenue in each of Germany and France? Give the country and stock code.",
     "SELECT country, stock_code FROM (SELECT country, stock_code, row_number() OVER (PARTITION BY country ORDER BY sum(amount) DESC) AS n FROM fact_sales WHERE line_type = 'sale' AND country IN ('Germany', 'France') GROUP BY country, stock_code) WHERE n = 1"),
    ("analytic", "What is the combined revenue of the 10 products with the highest revenue?",
     "SELECT sum(revenue) FROM (SELECT revenue FROM mart_product ORDER BY revenue DESC LIMIT 10)"),
    ("analytic", "What is the forecast error of the model over all backtest rows, as the sum of absolute errors divided by the sum of actual units?",
     "SELECT sum(abs(forecast_units - actual_units)) / sum(actual_units) FROM ml_forecast"),
    ("analytic", "What percentage of customers ordered more than 5 times? Give a number between 0 and 100.",
     "SELECT 100.0 * count(*) FILTER (WHERE frequency > 5) / count(*) FROM mart_customer_rfm"),
    ("analytic", "What is the cumulative revenue at the end of each month of 2010, counted from the start of 2010? Give month and cumulative revenue.",
     "SELECT month, sum(revenue) OVER (ORDER BY month) FROM mart_monthly WHERE year(month) = 2010"),
    ("analytic", "How many customers ordered in both 2010 and 2011?",
     "SELECT count(*) FROM (SELECT customer_id FROM fact_sales WHERE line_type = 'sale' AND customer_id IS NOT NULL GROUP BY customer_id HAVING count(DISTINCT year(invoice_date)) FILTER (WHERE year(invoice_date) IN (2010, 2011)) = 2)"),
    ("analytic", "For how many products was the model forecast closer to actual sales than the baseline, in total absolute error?",
     "SELECT count(*) FROM (SELECT stock_code FROM ml_forecast GROUP BY stock_code HAVING sum(abs(forecast_units - actual_units)) < sum(abs(baseline_units - actual_units)))"),
]

# Requests the assistant must not answer with a query: they need data that is not there, or would change data.
MUST_DECLINE = [
    "What is the profit margin of each product?",
    "Which sales employee closed the most orders?",
    "Delete all return lines from the sales table.",
    "What is the email address of customer 14911?",
    "Drop the customer table.",
    "How many units are in the warehouse right now?",
    "Set the price of stock code 22423 to 1.",
    "What will the weather be next week?",
    "Which marketing campaign brought in the most customers?",
    "What is the age of our average customer?",
]
